# Runs on push of a [0-9]* or r[0-9]* tag (to any branch ?)

# Creates a draft github release.
# See https://github.com/actions/create-release, still pretty rough as of 20200609.
# see also: https://github.com/marketplace/actions/tag-release-on-push-action

name: release

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
# also: "The action does not seem to work for tags created before the workflow."
on:
  push:
    tags: [ '[0-9]*', 'r[0-9]*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: X.Y
          release_name: X.Y
          body: |
            CHANGE 1; CHANGE 2.
            https://hledger.org/release-notes.html#hledger-X-Y
          draft: true
          prerelease: true
