name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker-arm32v7/Dockerfile
          platforms: linux/arm
          push: true
          tags: thecount2a/hledger-arm32v7:latest

      - name: Extract binaries from docker
        run: |
          # Create temporary container from it
          container_id=$(docker create thecount2a/hledger-arm32v7:latest)
          # Copy stuff from temp container
          docker cp $container_id:/hledger/hledger/Hledger/ /tmp/
          # Delete temp container
          docker rm -v $container_id

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: Static Binary
          path: /tmp/
