name: linux CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fossa/haskell-static-alpine:ghc-8.10.4
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Update cabal
      run: cabal update

    - name: Build on alpine
      run: cabal build --enable-executable-static all

    - name: Extract and strip binaries
      run: |
        mkdir /tmp/hledger
        cp dist-newstyle/build/x86_64-linux/ghc-*/hledger-web-*/x/hledger-web/build/hledger-web/hledger-web /tmp/hledger/
        cp dist-newstyle/build/x86_64-linux/ghc-*/hledger-ui-*/x/hledger-ui/build/hledger-ui/hledger-ui /tmp/hledger/
        cp dist-newstyle/build/x86_64-linux/ghc-*/hledger-*/x/hledger/build/hledger/hledger /tmp/hledger/
        strip /tmp/hledger/hledger-web
        strip /tmp/hledger/hledger-ui
        strip /tmp/hledger/hledger

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: Static Binaries
        path: /tmp/hledger
